import numpy as np
from inspect_ai.log import read_eval_log
from do_llms_know_what_theyre_capable_of._vendor.roc_comparison.compare_auc_delong_xu import delong_roc_variance

def find_auroc_and_predicted_success(predict_log_file, benchmark_log_file):
    """
    Computes AUROC, Predicted success rate, and True success rate for Experiment 1
    
    Args:
        predict_log_file: filepath to .eval file generated by bcb_predict.py
        benchmark_log_file: filepath to .eval file generated by bcb_benchmark.py
    """

    predict_log = read_eval_log(predict_log_file)
    model = predict_log.eval.model
    predictions = np.array([s.scores["percentage"].value for s in  predict_log.samples])

    benchmark_log = read_eval_log(benchmark_log_file)
    assert benchmark_log.eval.model==model, "Models in predict_log and outcomes_log don't match."
    IC_to_01 = {"I":0,"C":1}
    outcomes = np.array([IC_to_01[s.scores["verify"].value] for s in  benchmark_log.samples])

    auroc, auroc_var = delong_roc_variance(outcomes, predictions)
    predicted_success_rate = np.sum(predictions)/100 / len(predictions)
    true_success_rate = np.sum(outcomes) / len(outcomes)

    print("Model: ", model)
    print(f"AUROC: {auroc} ± {1.96*auroc_var**0.5} (95% CI, DeLong's method)")
    print("Predicted Sucess Rate: ", predicted_success_rate)
    print("True Success Rate: ", true_success_rate)
    return auroc, predicted_success_rate, true_success_rate

if __name__=="__main__":
    predict_log_file = "example_results/gpt-4o/predict/FULL.eval"
    outcomes_log_file = "example_results/gpt-4o/benchmark/FULL.eval"
    find_auroc_and_predicted_success(predict_log_file, outcomes_log_file)
    